name: hello
on:
  push:
    branches: [ source ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environments
        run: yarn install
      - name: Build
        run: yarn build
      - name: check
        run: ls -al build
