name: hello
on:
  push:
    branches: [ source ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environments
        run: yarn install
      - name: Build
        run: yarn build
      - name: Push to master
        run: |
          pushd build
          
          git init
          git remote add origin https://github.com/stwind/stwind.github.io.git
          git pull origin master

          git add -A
          git commit -m "Site updated at $(date +%Y-%m-%dT%H:%M:%S)"
          git push origin master
