name: hello
on:
  push:
    branches: [ source ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environments
        run: yarn install
      - name: Build
        run: yarn build
      - name: Push to master
        run: |
          set -euxo pipefail
          
          pushd build
          
          git init
          git remote add origin 'https://stwind:${{ secrets.GITHUB_TOKEN }}@github.com/stwind/stwind.github.io.git'

          git add -A
          
          git config --local user.email "stwindfy@gmail.com"
          git config --local user.name "stwind"
          
          git commit -m "Site updated at $(date +%Y-%m-%dT%H:%M:%S)"
          git push -f origin master
